version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: ecommerce_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Dee
      MYSQL_DATABASE: fantasy
      MYSQL_USER: disco
      MYSQL_PASSWORD: Dee
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
