   CREATE TABLE product (
       id BIGINT AUTO_INCREMENT PRIMARY KEY,
       title VARCHAR(255) NOT NULL,
       description TEXT NOT NULL,
       price DECIMAL(10, 2) NOT NULL,
       image_url VARCHAR(255),
       category VARCHAR(100) NOT NULL,
       rating DECIMAL(3, 2) NOT NULL,
       review_count INT NOT NULL DEFAULT 0,
       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
       version BIGINT NOT NULL DEFAULT 0
   );