spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: default
    baseline-on-migrate: true
    out-of-order: false

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      properties:
        hibernate:
          cache.use_second_level_cache: true
          cache.use_query_cache: false
          generate_statistics: true
          show_sql: true
          use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      fantasydrawer:
        ecommerce:
          controller: debug
          service: debug
          repository: debug
          model: debug

---
spring:
  config:
    activate:
      on-profile: prod

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: default
    baseline-on-migrate: true
    out-of-order: false

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ecommerce_db}?useSSL=${MYSQL_USE_SSL:false}&serverTimezone=UTC
    username: ${MYSQL_USER:prod_user}
    password: ${MYSQL_PASSWORD:prod_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format_sql: true
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      fantasydrawer:
        ecommerce:
          controller: debug
          service: debug
          repository: debug
          model: debug

