spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://mysql-db:3306/fantasy?useSSL=true&serverTimezone=UTC
    username: disco
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    schemas: fantasy

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true

logging:
  level:
    org.flywaydb.core: DEBUG
