spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3307/fantasy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: disco
    password: Dee
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history
    url: jdbc:mysql://localhost:3307/fantasy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    user: disco
    password: Dee
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Flyway handles schema
    show-sql: true    # Optional: logs SQL
    properties:
      hibernate:
        use_sql_comments: true
